# Lets run on the new infrastructure
sudo: false
dist: trusty

language: python
python:
  - "2.7"

install:
  - pip install tox

# before_script:
#   - wget http://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
#   - mkdir chromedriver
#   - unzip chromedriver_linux64.zip -d chromedriver
#   - export PATH=$PATH:$PWD/chromedriver

script:
  - ./scripts/prepare_server.sh
  - ./scripts/start_server.sh
  # - SELENIUM_DRIVER="selenium.webdriver.Chrome" tox -e docs-strict
  - tox -e docs-strict
  - tox -e docs-text-index
  - cp -r docs/_build/text/* docs/_build/html/_sources

after_script:
  - ./scripts/teardown_server.sh

after_failure:
  - cat server.log

deploy:
  - provider: pages
    local_dir: docs/_build/html
    repo: aristotle-mdr/aristotle-mdr.github.io
    target_branch: master
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: publish

  - provider: pages
    local_dir: docs/_build/html
    repo: aristotle-mdr/user-documentation
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: draft

  - provider: pages
    local_dir: docs/_build/html
    repo: aristotle-mdr/published-documentation
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: publish

# addons:
#   apt:
#     sources:
#       - google-chrome
#     packages:
#       - google-chrome-stable
