# Lets run on the new infrastructure
# sudo: false
# dist: trusty

# lets run on the old
# sudo: required 
dist: trusty
group: deprecated-2017Q4

language: python
python:
  - "3.6"

install:
  - pip install tox pipenv==2018.7.1

before_script:
  - sh ./scripts/get_chrome.sh
  - sh ./scripts/start_chrome.sh
  - printf "machine github.com\nlogin legostormtroopr\npassword ${GITHUB_TOKEN}" > ~/.netrc

addons:
  chrome: stable

script:
  - ./scripts/prepare_server.sh
  - ./scripts/start_server.sh
  - cp builder.env .env
  - pipenv install .
  - pipenv run sphinx-build -aE -b html docs/ docs/_build/html/
  # - tox -e docs-strict
  # - tox -e docs-text-index
  # - cp -r docs/_build/text/* docs/_build/html/_sources

after_script:
  - ./scripts/teardown_server.sh

after_failure:
  - cat server.log

deploy:
  - provider: pages
    local_dir: docs/_build/html
    repo: aristotle-mdr/published-documentation
    target-branch: draft
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: draft

  - provider: pages
    local_dir: docs/_build/html
    repo: aristotle-mdr/published-documentation
    target-branch: published
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: publish

# addons:
#   apt:
#     sources:
#       - google-chrome
#     packages:
#       - google-chrome-stable
